Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.WORKER_VERIFICATION_STATUS = exports.USER_STATUS = exports.TRANSACTION_DIRECTION = exports.SUPPORT_TICKET_STATUS = exports.SITE_STATUS = exports.SITE_ASSIGNMENT_STATUS = exports.SALARY_LEDGER_TYPE = exports.ROLE_KEYS = exports.REQUEST_STATUS = exports.PAYROLL_STATUS = exports.DOCUMENT_VERIFICATION_STATUS = exports.DOCUMENT_TYPE = exports.ATTENDANCE_STATUS = void 0;
// Single source of truth for every status/enum string used anywhere in the system.
// Never redeclare these inline in a frontend or backend file — import them.

const ROLE_KEYS = exports.ROLE_KEYS = ["SUPER_ADMIN", "MANAGER", "WORKER"];
const USER_STATUS = exports.USER_STATUS = ["ACTIVE", "SUSPENDED", "PENDING_VERIFICATION"];
const WORKER_VERIFICATION_STATUS = exports.WORKER_VERIFICATION_STATUS = ["PENDING_VERIFICATION", "DOCUMENT_VERIFIED", "WORK_TYPE_VERIFIED", "ACTIVE", "REJECTED"];
const SITE_STATUS = exports.SITE_STATUS = ["PLANNING", "ACTIVE", "ON_HOLD", "COMPLETED", "CANCELLED"];
const SITE_ASSIGNMENT_STATUS = exports.SITE_ASSIGNMENT_STATUS = ["ACTIVE", "ENDED", "TRANSFERRED"];
const ATTENDANCE_STATUS = exports.ATTENDANCE_STATUS = ["PRESENT", "ABSENT", "HALF_DAY", "LEAVE_PAID", "LEAVE_UNPAID", "CUSTOM"];
const SALARY_LEDGER_TYPE = exports.SALARY_LEDGER_TYPE = ["EARNING", "OVERTIME", "ADVANCE_DEDUCTION", "KHARCHI_DEDUCTION", "ADJUSTMENT", "REVERSAL"];
const PAYROLL_STATUS = exports.PAYROLL_STATUS = ["DRAFT", "CALCULATED", "REVIEW", "FINALIZED", "PAID"];
const REQUEST_STATUS = exports.REQUEST_STATUS = ["REQUESTED", "APPROVED", "PARTIALLY_APPROVED", "REJECTED", "PAID", "CANCELLED"];
const TRANSACTION_DIRECTION = exports.TRANSACTION_DIRECTION = ["INCOME", "EXPENSE"];
const DOCUMENT_TYPE = exports.DOCUMENT_TYPE = ["AADHAAR", "PAN", "DRIVING_LICENCE", "VOTER_ID", "PASSPORT", "PROFILE_PHOTO", "PAYMENT_PROOF", "EXPENSE_RECEIPT", "OTHER"];
const DOCUMENT_VERIFICATION_STATUS = exports.DOCUMENT_VERIFICATION_STATUS = ["PENDING", "VERIFIED", "REJECTED"];
const SUPPORT_TICKET_STATUS = exports.SUPPORT_TICKET_STATUS = ["OPEN", "IN_PROGRESS", "RESOLVED", "CLOSED"];